blueprint:
  name: Dynamic Timer Light Color Transition
  description: This blueprint transitions a light's color smoothly from red to green or green to red based on the progress of a selected timer.
  domain: automation
  input:
    timer_select:
      name: Select Timer
      description: The timer entity
      selector:
        entity:
          domain: timer
    light_select:
      name: Select Light
      description: The light entity to change color
      selector:
        entity:
          domain: light
    direction:
      name: Transition Direction
      description: Choose the direction of the color transition
      selector:
        select:
          options:
            - red_to_green
            - green_to_red

trigger:
  - platform: state
    entity_id: !input timer_select
    to: active
    from: idle

condition: []

action:
  - repeat:
      while:
        - condition: state
          entity_id: !input timer_select
          state: active
      sequence:
        - variables:
            selected_timer: !input timer_select
            duration: "{{ state_attr(selected_timer, 'duration') }}"
            parts: "{{ duration.split(':') }}"
            dhours: "{{ parts[0] | int }}"
            dminutes: "{{ parts[1] | int }}"
            dseconds: "{{ parts[2] | int }}"
            timer_duration: "{{ (dhours * 3600 + dminutes * 60 + dseconds) }}"
            finish_at: "{{ state_attr(selected_timer, 'finishes_at') }}"
            seconds: "{{ (as_timestamp(finish_at) - as_timestamp(now())) | int }}"
            hue: >-
              {% if (seconds / timer_duration) * 120 >= 0 and direction == 'red_to_green' %}
                {{ (seconds / timer_duration) * 120 }}
              {% else %}
                {{ 120 - ((seconds / timer_duration) * 120) }}
              {% endif %}
        - service: light.turn_on
          data:
            hs_color:
              - "{{ hue | round(0) }}"
              - 100
          target:
            entity_id: !input light_select
        - delay:
            seconds: 15
  - service: light.turn_on
    data:
      hs_color:
        - >-
          {% if direction == 'red_to_green' %}
            120
          {% else %}
            0
          {% endif %}
        - 100
    target:
      entity_id: !input light_select

mode: single
